name: Acme.sh
version: 1.0.0
slug: acmesh
description: Full ACME client to generate and renew a SSL certificate
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: services
map:
- ssl:rw
boot: auto
options:
  accountemail: null
  domains: null
  dns: null
  dnsEnvVariables: null
  keylength: '2048'
  fullchainfile: fullchain.pem
  keyfile: privkey.pem
  server: letsencrypt
schema:
  accountemail: str
  domains:
  - str
  dns: str
  dnsEnvVariables:
  - name: str
    value: str
  keylength: match(2048|4096|ec-256|ec-384|ec-521)
  server: match(letsencrypt|zerossl)
  fullchainfile: str
  keyfile: str
